language: node_js
node_js:
  - "0.12"
  - "0.10"
  - "iojs"

before_install:
  - npm install -g testem bower gulp
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - bower install

cache:
  directories:
    - bower_components
    - node_modules
